appcelerator/windowslib

- lib/windowsphone.js
- Initialize _results.windowsphone_ to not be _null_
[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-18706)
> [TIMOB-18706] Fix error when Windows Phone SDK is NOT installed

- CHANGELOG.md
- lib/certs.js
- lib/emulator.js
- lib/env.js
- lib/winstore.js
- package.json
More flags to help avoid the first time powershell subprocess hang. I was still seeing it locally, and am seeing it on the build machine as well.
I was able to reliably reproduce by opening a branch new cmd shell and trying to build an app. That would hang the first time for me. Killing and retrying in that same shell would work.
But with these changes the first ti build after opening a new cmd worked for me.
> Powershell hang fix, part two

- lib/wptool.js
- test/test-emulator.js
Fix unit test failure for `emulator` on Windows 10. It was because `Windows Phone 8.0` sdk returns empty array when you get list of available emulators on Windows 10. I just added array range check in this PR but we might want to just deprecate 8.0 sdk and always prefer 8.1.
> Fix: emulators test failed on Windows 10

- lib/winstore.js
Remove deploy command check at winstore.deploy because `deployCmd` is not actually used for Windows Store apps. This also removes `Windows Store SDK is missing the deploy command` error message at `appc setup` on Windows, which is not quite right.
```
$ appc setup
...
The following WINDOWS issues were found in your environment:
Microsoft Windows Store SDK is missing the deploy command.
You will be unable to build Windows Store apps.
Some issues were detected for your environment
Please review the above found issues that were detected for your environment.
You should resolve these issues before building or running a cross platform app.
You can re-run setup once they are resolved to validate.
appc setup complete!
```
> Remove error message for Windows Store deploy command

- lib/visualstudio.js
`visualstudio.detect` failed when install path contains space. I saw `vcvarsall` contains space for Visual Studio 2015 on Windows 8.1, which is installed into the default location (C:\Program Files (x86)\Microsoft Visual Studio 14.0). Interestingly `vcvarsall` for Visual Studio 2013 does not contains space at the time. Either way it's safer to always escape the space.
> Fix: visualstudio.detect failed when install path contains space

- lib/certs.js
- lib/visualstudio.js
- lib/winstore.js
- package.json
- test/test-winstore.js
- wstool/wstool.cs
Fix for [TIMOB-19693](https://jira.appcelerator.org/browse/TIMOB-19693).
- Fix: `vsInfo.vcvarsall` should escape space when command is used with `&&`
- Fix: `winstore.launch` doesn't launch Windows 10 Store app
> Fix: winstore.launch doesn't launch on Windows 10

- lib/certs.js
- lib/visualstudio.js
- Fix: Make sure to escape `vcvarsall` at `subprocess.run`
- Fix: Stop using /m at msbuild
Spaces in `vcvarsall` should be escaped in `subprocess.run` when it is used with `&&`, it may cause error when both Visual Studio 2013 and 2015 are installed. Also, stop using `/m` at MsBuild due to [TIMOB-19646](https://jira.appcelerator.org/browse/TIMOB-19646).
@sgtcoolguy, could you bump up the version and update [titanium_mobile](https://github.com/appcelerator/titanium_mobile) so that it points to the new version? Thanks.
> Fix: escape vcvarsall before subprocess.run

- lib/windowsphone.js
- lib/wptool.js
- Only list the 8.1 emulators for 8.1 and 10.0 for 10.0 SDKs.
- Detect Windows 10 mobile details (sort of)
- for now this cheats and uses the 8.1 signtool and deploy command. That's the only way we can get the Win 10 emulator listing. But as [detailed here](https://jira.appcelerator.org/browse/TIMOB-20095) I can't find any way to get an app deployed to the emulator using new or old tooling.
> Fixes for Windows 10 Phone

- CHANGELOG.md
- index.js
- lib/utilities.js
- lib/windowsphone.js
- lib/wptool.js
- package.json
- test/test-windowsphone.js
- We now detect 8.0/8.1 and 10 in parallel. Before we'd look for 8.0/8.1 first and if we didn't find one of those we wouldn't try to get win 10.
- Should be slightly faster detection now because of that?
- Mark 8.1/8.0 supported flag as "false" if we can't find the deploy command, that means by default Windows 10 will be "selected" if we find entries for 8.1 but not the tooling.
- Tested by removing my windows 8.1 SDK/tooling through VS2015 Update 1. It actually keeps some stuff around (like XapSignTool), but removes the AppDeployCmd and in that case we list 8.1 in our entry but as unsupported and 10 is chosen as the preferred/selected.
https://jira.appcelerator.org/browse/TIMOB-20198
> Bump to 0.3.0, support Windows 10 detection/usage without requiring 8.1 tooling as well

- lib/wptool.js
- test/test-wptool.js
https://jira.appcelerator.org/browse/TIMOB-20096
I don't have a windows 10 phone to test this with, so hopefully @infosia you can? I did connect my Windows 8.1U1 phone via USB and got it listed in the WinAppDeployCmd output, but couldn't test installing an app to it (since it's not a Win 10 mobile device!)
Basically we just run {{WinAppDeployCmd.exe devices 2}} to gather a list of devices and parse it using a regex, similar to how we parse the Windows 8.1 AppDeployCmd.exe output for emulators.
If a pin is required to pair to a device the first time, we just fail miserably (I assume). Likely we'd want to output at least a message asking the user to install the app once with their device pin and basically spit out the exact command line they should use (with <pin> placeholder arg). I just …
> Enumerate Windows 10 devices using WinAppDeployCmd

- lib/winstore.js
- test/test-winstore.js
These are changes to support the ability to get metadata about Windows runtime apps, which are required to exempt apps from the loopback ip network block. This is a change required to fix https://jira.appcelerator.org/browse/TIMOB-20370
Basically we call `powershell Get-AppxPackage` and turn the results into JSON where the keys are the app Name value and the set of key/value pairs are stored on the object. That way we can look up an app by it's "Name" (which should match our appId!) and then ask for details about the app from windows knowledge (like `PackageFamilyName`, which we need to exempt the app from network isolation for loopback IP). We happened to do something close where we just looked for one key/value pair to find the `PackageFullName` for when we uninstalled previously …
> Parse Get-AppxPackage output into JSON

- bin/wp_get_appx_metadata.ps1
- lib/process.js
- lib/utilities.js
- lib/winstore.js
- lib/wptool.js
- test/test-device.js
- test/test-emulator.js
- test/test-process.js
- test/test-winstore.js
- wstool/wstool.cs
- Make wstool return pid after launching app.
- Move common code to utilities for checking if wptool/wstool need to be rebuilt.
- Add method for loopback exempting a Windows Store app by id/Name.
- Add a unit test for winstore.getAppxPackages()
- Fix broken wp_get_appx_metadata.ps1 file from newline mid-line
> Move loopbackExempt into windowslib

- lib/wptool.js
- package.json
- wptool/wptool.cs
- Add support for Windows 10 devices into ```wptool.cs```
- Add additional error reporting into ```wptool.js```
NOTE: Currently, it seems physical Windows 10 devices cannot be used with ```Microsoft.SmartDevice.MultiTargeting.Connectivity```
[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-20566)
> [TIMOB-20566] Add support for Windows 10 devices

- lib/certs.js
Improve log output when `certutil` fails. It includes actual output as well as JavaScript error.
> Improve log output from certutil

- lib/wptool.js
Fix for [TIMOB-23181](https://jira.appcelerator.org/browse/TIMOB-23181)
Fix `[ERROR] Failed to install app (code 0x80073CFB): Deployment of package xxx was blocked because the provided package has the same identity as an already-installed package but the contents are different. Increment the version number of the package to be installed, or remove the old package for every user on the system before installing this package.`. This fix basically tries to uninstall-then-install app when it has `0x80073CFB` error. This only happens on Windows 10 Mobile.
> [TIMOB-23181] Install app for Windows 10 Mobile fails on second install

- lib/wptool.js
- package.json
- Prevent device listings from ``wptool`` being overwritten by listings from ``winAppDeploy``
[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-20571)
> [TIMOB-20571] Combine device listings

- wptool/wptool.cs
- Fix ``launch`` command functionality for Windows 10 devices
[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-20611)
> [TIMOB-20611] Allow wptool to launch Windows 10 apps

- index.js
- lib/device.js
- lib/emulator.js
- lib/wptool.js
- wptool/wptool.cs
- When installing app to device, don't re-enumerate the devices, use the cached listing if possible
- fix error message when unable to find device with same udid (udid was always reported as undefined before)
- retain device ip/running flag after connecting in install (to avoid need to connect again)
- pass device/emulator object along with 'connected' event
- Add some FIXME markers
> [TIMOB-23253] Windows: Build errors when building to device and selecting second option in device prompt

- CHANGELOG.md
- lib/wptool.js
- package.json
- Prevent ``wptool.detect()`` from passing errors when a usable result is still obtainable
[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-23484)
> [TIMOB-23484] wptool.detect() ignore errors when results are present

- CHANGELOG.md
- lib/wptool.js
- package.json
- wptool/wptool.cs
- If a device has not been detected then no devices should be reported
- Skip any invalid devices detected by ``wptool`` (such as two devices at once, which is unsupported)
- Use ``wptool`` with ``8.1`` and ``10.0`` but not ``8.0`` (which is now unsupported)
[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-23279)
> [TIMOB-23279] Only report a device when one has been detected

- lib/wptool.js
[TIMOB-23749](https://jira.appcelerator.org/browse/TIMOB-23749)
`appc ti info -p windows -o json` does not list Windows Phone 8.1 emulators. 
*Steps to reproduce*
`appc ti info -p windows -o json`
*Expected*
Windows Phone 8.1 emulators are listed as well as Windows 10 Mobile emulators.
> [TIMOB-23749] "appc ti info" does not list WP 8.1 emulators

- CHANGELOG.md
- package.json
- wptool/wptool.cs
[TIMOB-23748](https://jira.appcelerator.org/browse/TIMOB-23748)
Titanium CLI is unable to connect to Windows Phone 8.1 device after updating to Microsoft Windows 10 SDK `10.0.14393`. There's no problem building against Windows 10 Mobile device though.
As far as I can see, it turns out that `Microsoft.SmartDevice.Connectivity.IDevice.GetEndPoints` throws Exception when you connect to Windows Phone 8.1 device. I found that it actually is able to connect to WP 8.1 device, and those information (that `IDevice.GetEndPoints` collects) are not actually used from Titanium CLI, so it's safe to return success=true.
> [TIMOB-23748] Failed to connect to WP 8.1 device

- CHANGELOG.md
- lib/wptool.js
- package.json
- Take appropriate action when handling duplicate package error `[ERROR] Error: Failed to install app (code 2148734208): Windows App Deployment Tool` caused by Windows SDK `10.0.14393`
```
appc run -p windows -T wp-device
appc run -p windows -T wp-device
```
[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-23762)
> [TIMOB-23762] Handle duplicate package error from Windows SDK 10.0.14393

- CHANGELOG.md
- lib/wptool.js
- package.json
[TIMOB-23800](https://jira.appcelerator.org/browse/TIMOB-23800)
*Steps to reproduce*
- Build an application to a Windows mobile device or emulator
- Without uninstalling the previous app, build a different app to a Windows mobile device or emulator
*Expected result*
As with previous SDKs the CLI should log an error to the user telling them to uninstall the other app
> [TIMOB-23800] CLI hangs on install of app when a different app installed

- CHANGELOG.md
- index.js
- package.json
- Implement `options.skipWpTool` to skip detection of Windows devices
[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-23834)
> [TIMOB-23834] Implement ability to skip windows phone device detection

- CHANGELOG.md
- lib/windowsphone.js
- lib/winstore.js
- package.json
Related to [TIMOB-23661](https://jira.appcelerator.org/browse/TIMOB-23661)
`preferredWindowsPhoneSDK` and `preferredWindowsSDK` should be the valid options to specify preferred Windows SDK version.
> [TIMOB-23661] Fix typo around preferred SDK

- CHANGELOG.md
- package.json
- wptool/wptool.cs
[TIMOB-23879](https://jira.appcelerator.org/browse/TIMOB-23879)
Make sure to terminate running app on launch. Interestingly terminating app right before _launch_ refreshes the app.
Steps to reproduce
1. Build an app using `appc run -p windows -T wp-device`
2. Once the app has launched, quit the process and *leave the app open on device*
3. Make an obvious change in the app, such as changing the background color
4. Rebuild the app `appc run -p windows -T wp-device`
5. Observe the app
Expected
App should be launched with new state (new background color etc).
> [TIMOB-23879] Terminate running app at launch

- CHANGELOG.md
- lib/winstore.js
- package.json
[TIMOB-24157](https://jira.appcelerator.org/browse/TIMOB-24157)
When we install Windows Store app, we need to ensure developer certificate installed first, and then it needs to be executed in a new Window to workaround user-input issue in Node.js (described in the ticket).
To see if you already installed developer certificate, launch “Manage user certificates” from control panel and navigate to “Trusted People > Certificates”. “CMake Test Cert” is the developer cert. You can remove it in order to test this issue.
```
appc run -p windows --wp-sdk 10.0 --target ws-local -l trace
```
> [TIMOB-24157] Install certificate in new window

- CHANGELOG.md
- lib/wptool.js
- package.json
[TIMOB-23976](https://jira.appcelerator.org/browse/TIMOB-23976)
`enumerate` should just return empty data when no results found with given version. It is because we tend to `enumerate` across Windows SDK (8.0, 8.1, 10.0) with use of multiple ways (native tooling, ws, wptool) and we don't want to throw error when one of them returns no data.
> [TIMOB-23976] enumerate should just move on when no results found

- CHANGELOG.md
- lib/logrelay.js
- package.json
Follow-up from #61. 
`node-uuid` got deprecated, we should use `uuid` instead for now.
> Update uuid to version 3.0.0

- CHANGELOG.md
- lib/wptool.js
- package.json
[TIMOB-24183](https://jira.appcelerator.org/browse/TIMOB-24183)
`appc run -p windows --target wp-device` fails to deploy apps to Windows Phone 8.1 device.
It turns out that deployment failed because outputs from Windows Phone deployment tools have been changed at some point of the installation, now it could output nothing but returns error code other than "0". As far as I can see it means deployment went successful and we can ignore the error code when output from tools are empty.
Note that this works with https://github.com/appcelerator/titanium_mobile_windows/pull/915 and you need to update windowslib in [titanium_mobile](https://github.com/appcelerator/titanium_mobile) in order to make this work.
> [TIMOB-24183] Failed to install WP 8.1 app

- CHANGELOG.md
- lib/visualstudio.js
- package.json
- test/test-visualstudio.js
[TIMOB-24189](https://jira.appcelerator.org/browse/TIMOB-24189)
I found interesting behavior while working on https://github.com/appcelerator/titanium_mobile_windows/pull/959, that is some VS batch tools (including `vcvarsall.bat`) does not work correctly when it is executed by [8.3 filenames](https://en.wikipedia.org/wiki/8.3_filename). We are usually using 8.3 filename when requiring `vcvarsall.bat` but it seems it does not work correctly under the situation. I'm also thinking that we should use `VsDevCmd.bat` instead because it's the file that Visual Studio Developer Console is using. We can safely replace it because  `VsDevCmd.bat` is available as of Visual Studio 2012.
> Use VsDevCmd instead of vcvarsall

- CHANGELOG.md
- lib/certs.js
- package.json
JIRA: https://jira.appcelerator.org/browse/TIMOB-24922
On VS2017 the cert generation process errors due to using vcvarsall, switching to using vsDevCmd fixes this.
Tested on VS2017 and VS 2015
Verification
1. Build an application using `appc run -p windows -T dist-phonestore`
2. Follow the prompts
- Cert should be created and packaging should be successful
> [TIMOB-24922] Fix cert generation on VS2017

- CHANGELOG.md
- bin/wp_get_appx_metadata.ps1
- lib/wptool.js
- package.json
JIRA: https://jira.appcelerator.org/browse/TIMOB-24683
It looks like in VS2017 it is possible to install a Windows 10 SDK and there not be a winappdeploycmd (or VS is still not great at uninstalling cleanly). So if the deploycmdproperty does not exist don't try and detect devices
See jira
> [TIMOB-24683] Do not attempt to run winappdeploycmd if it does not exist

- CHANGELOG.md
- lib/windowsphone.js
- package.json
JIRA: https://jira.appcelerator.org/browse/TIMOB-24958
After detecting the 'globally installed' winappdeploycmd,
- Search through the bin directory for folders that match a regex  for the 10 SDK. 
- Search the bin\x86 folder of each SDK for winappdeploycmd.exe
This means that we moving forward we will take the highest version of the tool on the system (also just to call out what the differences are the one under 10.0.15063 has a -preserveAppData flag which might be useful for us).
For example: 
- VS 2017 with only 10.0.15063.0 will take the winappdeploycmd under `C:\Program Files (x86)\Windows Kits\10\bin\10.0.15063.0\x86`
- VS 2017 with 10.0.15063.0 and 10.0.14393.0 will take the winappdeploycmd under `C:\Program Files (x86)\Windows Kits\10\bin\10.0.15063.0\x86`
- VS 2017 with only …
> [TIMOB-24958] Fix detection of SDK specific winappdeploycmd

- .travis.yml
The c# image gave us nothing over the node_js image (they both run the same number of tests) and this allows us to check our code against a range of node versions (plus it actually works)
> Use node_js image on travis

- CHANGELOG.md
- lib/visualstudio.js
- lib/wptool.js
- package.json
[TIMOB-25232](https://jira.appcelerator.org/browse/TIMOB-25232)
I was not able to reproduce this particular issue, but we need to make sure `JSON.parse` not throw error when enumerating environmental information.
> [TIMOB-25232] Make sure to catch JSON.parse errors

- .gitignore
- .npmignore
- CHANGELOG.md
- lib/wptool.js
- package-lock.json
- package.json
- test/test-wptool.js
- If the user of this library specifies the supportedWindowsPhoneSDKVersions option then we will only detect and report the emulators for that version
- Added coverage to the library. I only added coverage to the main mocha test run as adding to the others seems pointless given that they only target a single file. Current results are below, I don't believe it's enforcing any percentage right now but I need to double check (update, travis passed so yeah there is no enforcement of percentages currently)
````
------------------|----------|----------|----------|----------|----------------|
File              |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
------------------|----------|----------|----------|----------|----------------|
All files         |    59.77 |    47.37 | …
```
> [TIMOB-25027] Filter emulators based off supportedWindowsPhoneSDKVersions  parameter

- CHANGELOG.md
- lib/wptool.js
- package.json
If the total path length of ``__dirname\wptool\bin\Release\<longest_assembly_name>`` is greater than or equal to max path, then we will move the wptool project to os.tmpDir() and build there..
~~I'm still trying to decide on a best course of action if the ``__dirname\bin`` directory proves too long to copy to, as we will have to consider this when calling checkOutdated too~~
Edit: The above is unecessary, a user with the max allowed username does not trigger an error copying the files to bin
> [DAEMON-165] Handle max path when building wptool

- CHANGELOG.md
- lib/wptool.js
- package-lock.json
- package.json
[TIMOB-25616](https://jira.appcelerator.org/browse/TIMOB-25616)
Windowslib have been uninstalling existing app in order to complete the installation when same version of the app is already installed, but we should not uninstall existing app unless user explicitly specifies `forceUnInstall`option. It should ends up showing error message when `forceUnInstall=false` and there's same version of the app installed, which should be the default behavior of `wpToolInstall`.
> [TIMOB-25616] Don't forceUnInstall unless user explicitly specifies it

- CHANGELOG.md
- lib/wptool.js
- package-lock.json
- package.json
[TIMOB-25827](https://jira.appcelerator.org/browse/TIMOB-25827)
Expected:
1. Build an application for wp-emulator with the emulator closed (clean state) with `--forceUnInstall`
2. Build should not fail
Also make sure [TIMOB-23800](https://jira.appcelerator.org/browse/TIMOB-23800) doesn't happen again
1. Build an application
2. Without uninstalling an app, build an app with same `<guid>` with different `<id>` in `tiapp.xml`
3. Build should error out with `A debug application is already installed, please remove existing debug application.`
4. After uninstalling an app manually, build should not fail then.
> [TIMOB-25827] Error when fresh install with forceUnInstall

- package.json
github recently alerted [potential security vulnerability in dependencies in moment package before 2.19.3](https://nvd.nist.gov/vuln/detail/CVE-2017-18214). I believe this has to be small impact for windowslib because no dates are generated from strings but I would like to suppress the warning.
> [CVE-2017-18214] Fix potential security vulnerability in moment

- CHANGELOG.md
- lib/wptool.js
- package-lock.json
- package.json
[TIMOB-24422](https://jira.appcelerator.org/browse/TIMOB-24422)
Windows App Deployment Tool fails with following error but we need to continue launching app because application is actually installed in this case.
```
0x80131500 - Failed to install or update package: Unspecified error 
'Microsoft Platform Extensions' violates pattern constraint of '\bms-resource:.{1,256}'.
```
> [TIMOB-24422] Fix deployment issue with "violates pattern constraint"

- test/test-emulator.js
Do we still need to support <= 8.1?
> Skip 8.1 launch test

- lib/certs.js
- package-lock.json
- package.json
- test/test-certs.js
if the consuming code throws an error in it's callback handler, the thumbprint method could call the callback twice.
This fixes that behavior and adds a test to verify the fix.
> fix(certs): double callback on thumbprint
